language: python
python:
  - '3.6'
install: pip install --ignore-installed -r requirements.txt && pip install --ignore-installed -r requirements-dev.txt
script:
 - nosetests
 - flake8 --config setup.cfg tachyon test
